# -*- coding: utf-8 -*-
"""multi_policy_rag_orchestrator_v3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LoijfFrfDWBe87srIDKTaTOIwFdSbPIv

# Multi-Policy RAG — **Version 3**

**Medical + Dental policies, intent-aware orchestrator, persistent indexes, and a strict-prompt teaching demo.**

Version 3 incorporates four upgrades over the previous notebook, each one a deliberate teaching point.

| # | Upgrade | Why it matters in class |
|---|---------|--------------------------|
| 1 | **LLM tool-calling orchestrator** with two `Tool` objects (`search_medical_policy`, `search_dental_policy`) — the orchestrator now *reasons* about which policy to consult based on intent, instead of hard-coding "medical first." | Lets students compare deterministic routing vs. agentic routing on the same specialists. The deterministic fallback rule is preserved as a safety net. |
| 2 | **Strict-vs-weak `NOT_FOUND` demo.** A side-by-side cell shows what happens when the specialist prompt's `NOT_FOUND` rule is softened. | Makes the prompt-engineering contract behind the fallback chain visible — and breakable. |
| 3 | **Provenance.** Every retrieved chunk carries a `policy` tag in its metadata, surfaced in the UI's source list. | Students can audit which document any quoted phrase came from. |
| 4 | **Persistent FAISS indexes.** `vs.save_local(...)` / `FAISS.load_local(...)` means the PDFs are embedded **once**; subsequent runs reload from disk in seconds. | Production hygiene + a much faster classroom demo loop. |

### Architecture (v3)

```
                        ┌────────────────────────────────┐
                        │  Tool-calling Orchestrator     │
                        │  (LLM picks the tool based on  │
                        │   query intent; falls back to  │
                        │   the other tool on NOT_FOUND) │
                        └──────────────┬─────────────────┘
                                       │ tool calls
                       ┌───────────────┴───────────────┐
                       ▼                               ▼
              ┌──────────────────┐            ┌──────────────────┐
              │ search_medical_  │            │ search_dental_   │
              │ policy(query)    │            │ policy(query)    │
              └────────┬─────────┘            └────────┬─────────┘
                       │                               │
                       ▼                               ▼
              ┌──────────────────┐            ┌──────────────────┐
              │ MedicalAgent     │            │ DentalAgent      │
              │ FAISS (on disk)  │            │ FAISS (on disk)  │
              └──────────────────┘            └──────────────────┘
```

## 1. Install dependencies
"""

#!pip install -q -U langchain langchain-core langchain-openai langchain-community langchain-text-splitters faiss-cpu pypdf tiktoken
# In Colab, restart the runtime after this finishes the FIRST time (Runtime ▸ Restart session).
#!pip install -q pdfplumber
#!pip install -q PyMuPDF

"""## 2. Imports and API key"""

import os
import json
import getpass
from pathlib import Path
from typing import List, Optional

# LangChain (modern, post-split packages only — no `langchain.chains`)
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_community.document_loaders import PyPDFLoader
from langchain_community.vectorstores import FAISS
from langchain_community.document_loaders import PDFPlumberLoader
from langchain_community.document_loaders import PyMuPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.tools import tool
from langchain_core.messages import HumanMessage, SystemMessage, ToolMessage, AIMessage

# UI
#import ipywidgets as widgets
#from IPython.display import display, Markdown, clear_output

# Where persisted FAISS indexes live
INDEX_DIR = Path("faiss_indexes")
INDEX_DIR.mkdir(exist_ok=True)
MEDICAL_INDEX_PATH = INDEX_DIR / "medical_index"
DENTAL_INDEX_PATH  = INDEX_DIR / "dental_index"

print("Environment ready.")

import os
from google.colab import userdata

#Set the OpenAI key using ColabServices
os.environ["OPENAI_API_KEY"] = userdata.get('OPENAI_API_KEY')
LLM_MODEL = "gpt-4o-mini"
EMBED_MODEL = "text-embedding-3-small"

print("LLM API ready")

"""## 3. Build (or reload) the vector store

This is upgrade **#4 — Persistent FAISS indexes**. The helper first checks whether an index for
this policy already exists on disk; if it does, it reloads it instantly. Only the first run pays
the embedding cost.

> ⚠️ `FAISS.load_local(..., allow_dangerous_deserialization=True)` is required because FAISS
> indexes are stored as pickled Python objects. Only enable this for indexes you built yourself.

"""

def build_or_load_vectorstore(pdf_path: str, label: str, index_path: Path) -> FAISS:
    """Return a FAISS index for the given PDF, loading it from disk if available."""
    embeddings = OpenAIEmbeddings(model=EMBED_MODEL)

    if index_path.exists():
        print(f"[{label}] Reloading existing index from {index_path} ...")
        vs = FAISS.load_local(
            str(index_path),
            embeddings,
            allow_dangerous_deserialization=True,
        )
        print(f"[{label}]   Loaded.\n")
        return vs

    print(f"[{label}] Building new index from {pdf_path} ...")
    #loader = PyPDFLoader(pdf_path)
    #loader = PDFPlumberLoader(pdf_path)
    loader = PyMuPDFLoader(pdf_path)
    pages = loader.load()
    print(f"[{label}]   {len(pages)} pages loaded.")

    splitter = RecursiveCharacterTextSplitter(
        chunk_size=800,
        chunk_overlap=100,
        separators=["\n\n", "\n", ". ", " ", ""],
    )
    chunks = splitter.split_documents(pages)

    # ---- Upgrade #3: Provenance tag on EVERY chunk ----
    for c in chunks:
        c.metadata["policy"] = label
        c.metadata["source_file"] = os.path.basename(pdf_path)
    print(f"[{label}]   {len(chunks)} chunks created, all tagged with policy='{label}'.")

    vs = FAISS.from_documents(chunks, embeddings)
    vs.save_local(str(index_path))
    print(f"[{label}]   Index saved to {index_path}.\n")
    return vs


def clear_indexes():
    """Delete persisted indexes so the next build call re-embeds the PDFs."""
    import shutil
    for p in (MEDICAL_INDEX_PATH, DENTAL_INDEX_PATH):
        if p.exists():
            shutil.rmtree(p)
            print(f"Removed {p}")

"""## 4. Specialist agent (Medical or Dental) with the **strict** `NOT_FOUND` contract

Each specialist is a small LCEL chain `retriever → prompt → llm → parser`. The prompt is the
**strict version** — section 8 below contrasts it with a weakened version so students can see the
fallback chain break in real time.
"""

STRICT_PROMPT = (
    "You are a {policy_label} policy specialist. Answer the user's question using ONLY the "
    "context below, which is taken from the {policy_label} Policy document.\n\n"
    "STRICT RULES:\n"
    "1. If the context clearly contains the answer, provide a concise, factual answer and "
    "quote the most relevant phrase.\n"
    "2. If the context does NOT contain enough information to answer, you MUST reply with "
    "exactly this token and nothing else: NOT_FOUND\n"
    "3. Never use outside knowledge. Never guess.\n\n"
    "Context:\n{context}\n\n"
    "Question: {question}\n"
    "Answer:"
)

# Used in section 8 only — DO NOT use this for real queries.
WEAK_PROMPT = (
    "You are a {policy_label} policy specialist. Try to answer the user's question using the "
    "context below. If you're not sure, give your best guess based on general knowledge.\n\n"
    "Context:\n{context}\n\n"
    "Question: {question}\n"
    "Answer:"
)


def _format_docs(docs):
    return "\n\n---\n\n".join(d.page_content for d in docs)


class PolicyAgent:
    """A single-policy RAG specialist. Returns either a grounded answer or 'NOT_FOUND'."""

    def __init__(self, name: str, vectorstore: FAISS, llm: ChatOpenAI,
                 k: int = 4, prompt_template: str = STRICT_PROMPT):
        self.name = name
        self.vectorstore = vectorstore
        self.llm = llm
        self.k = k
        self.retriever = vectorstore.as_retriever(search_kwargs={"k": k})
        self._prompt = PromptTemplate(
            input_variables=["context", "question"],
            template=prompt_template.replace("{policy_label}", name),
        )
        self._chain = self._prompt | llm | StrOutputParser()

    def ask(self, question: str) -> dict:
        docs = self.retriever.invoke(question)
        context = _format_docs(docs)
        answer = self._chain.invoke({"context": context, "question": question}).strip()
        found = "NOT_FOUND" not in answer.upper().split()
        sources = [
            {
                "page": d.metadata.get("page"),
                "policy": d.metadata.get("policy", self.name),
                "source_file": d.metadata.get("source_file"),
                "snippet": d.page_content[:220].replace("\n", " ") + "...",
            }
            for d in docs
        ]
        return {"answer": answer, "found": found, "sources": sources}

"""## 5. Wire the specialists"""

#Upload the document (dental policy)
#from google.colab import files
#uploaded = files.upload()

MEDICAL_PDF = "HR_Policy_Medicalbenefits.pdf"  # change if needed
DENTAL_PDF  = "dental_benefits_summary.pdf"   # change if needed

# Module-level holders populated by build_system()
medical_agent: Optional[PolicyAgent] = None
dental_agent:  Optional[PolicyAgent] = None
orchestrator = None  # tool-calling orchestrator, defined in §6


def build_system(medical_pdf: str = MEDICAL_PDF, dental_pdf: str = DENTAL_PDF):
    """Build specialists + tool-calling orchestrator. Reloads indexes from disk if present."""
    global medical_agent, dental_agent, orchestrator

    llm = ChatOpenAI(model=LLM_MODEL, temperature=0)

    med_vs = build_or_load_vectorstore(medical_pdf, "Medical", MEDICAL_INDEX_PATH)
    den_vs = build_or_load_vectorstore(dental_pdf,  "Dental",  DENTAL_INDEX_PATH)

    medical_agent = PolicyAgent("Medical", med_vs, llm)
    dental_agent  = PolicyAgent("Dental",  den_vs, llm)

    orchestrator = ToolCallingOrchestrator(medical_agent, dental_agent, llm)
    print("System ready. Tool-calling orchestrator is online.")
    return orchestrator

"""## 6. The **LLM tool-calling orchestrator** (upgrade #1)

This is the headline change in version 3. Instead of a hard-coded "medical first" controller, we
expose each specialist as a `Tool` and let the LLM decide which one to call based on the query's
intent. A short system prompt teaches it the routing policy:

1. **Read the question and pick the more relevant policy** — obviously dental queries (cleanings,
   crowns, orthodontia, etc.) go straight to `search_dental_policy`; obviously medical queries
   (hospitalization, prescriptions, imaging) go straight to `search_medical_policy`. Ambiguous
   queries start with Medical.
2. **If the chosen tool returns `NOT_FOUND`**, the model is instructed to call the **other** tool
   before giving up.
3. **If both tools return `NOT_FOUND`**, the orchestrator finalises the answer as
   *"Not found in any policy."*

The full sequence of tool calls and tool results is captured as the **chain of thought** shown in
the UI.

> Why keep the deterministic version around too? Because the LLM router can occasionally pick the
> wrong tool first. The deterministic fallback inside the orchestrator (call the *other* tool when
> the first one says `NOT_FOUND`) is the safety net that makes the agentic version robust.

"""

# -------------------- Tools exposed to the LLM --------------------
@tool
def search_medical_policy(query: str) -> str:
    """Search the MEDICAL policy knowledge base. Use for questions about medical coverage,
    hospitalization, prescriptions, imaging, specialists, deductibles, etc.
    Returns either a grounded answer or the literal token 'NOT_FOUND'."""
    if medical_agent is None:
        return "ERROR: Medical agent not initialised. Call build_system() first."
    return medical_agent.ask(query)["answer"]

@tool
def search_dental_policy(query: str) -> str:
    """Search the DENTAL policy knowledge base. Use for questions about dental coverage,
    cleanings, fillings, crowns, root canals, orthodontia, periodontics, etc.
    Returns either a grounded answer or the literal token 'NOT_FOUND'."""
    if dental_agent is None:
        return "ERROR: Dental agent not initialised. Call build_system() first."
    return dental_agent.ask(query)["answer"]


ORCHESTRATOR_SYSTEM_PROMPT = (
    "You are an insurance benefits orchestrator with access to two tools: "
    "`search_medical_policy` and `search_dental_policy`.\n\n"
    "ROUTING POLICY:\n"
    "1. Read the user's question and pick the tool whose policy is more likely to contain the "
    "answer. Dental-specific queries (cleanings, fillings, crowns, root canals, orthodontia, "
    "periodontics, dentures) → search_dental_policy. Medical-specific queries (hospitalization, "
    "prescriptions, imaging, specialists, surgery, mental health) → search_medical_policy. "
    "Ambiguous queries → start with search_medical_policy.\n"
    "2. If the first tool returns 'NOT_FOUND', you MUST call the OTHER tool before answering.\n"
    "3. If both tools return 'NOT_FOUND', your final answer must be exactly: "
    "Not found in any policy.\n"
    "4. When a tool returns a real answer, return that answer to the user — do not paraphrase "
    "away the cited phrase.\n"
    "5. Never invent coverage details. Never use outside knowledge."
)


class ToolCallingOrchestrator:
    """LLM-driven orchestrator that picks tools by intent and falls back on NOT_FOUND."""

    NOT_FOUND_FINAL = "Not found in any policy."

    def __init__(self, medical: PolicyAgent, dental: PolicyAgent, llm: ChatOpenAI):
        self.medical = medical
        self.dental = dental
        # Bind both tools to the LLM so it can issue tool calls
        self.tools = [search_medical_policy, search_dental_policy]
        self.tools_by_name = {t.name: t for t in self.tools}
        self.llm = llm.bind_tools(self.tools)

    # ----- helper: run a specialist by name and capture sources too -----
    def _run_tool_with_sources(self, name: str, query: str):
        agent = self.medical if name == "search_medical_policy" else self.dental
        return agent.ask(query)  # returns {answer, found, sources}

    def answer(self, question: str, max_iters: int = 4) -> dict:
        cot: List[str] = []
        all_sources: List[dict] = []
        policies_consulted: List[str] = []

        cot.append(f"**Step 1 — User question:** _{question}_")
        cot.append("**Step 2 — Sending question to the LLM orchestrator with two tools bound.**")

        messages = [
            SystemMessage(content=ORCHESTRATOR_SYSTEM_PROMPT),
            HumanMessage(content=question),
        ]

        for it in range(max_iters):
            ai_msg: AIMessage = self.llm.invoke(messages)
            messages.append(ai_msg)

            if not ai_msg.tool_calls:
                # The model has produced its final answer
                final = (ai_msg.content or "").strip()
                cot.append(f"**Step {len(cot)+1} — LLM produced final answer:** _{final}_")
                # Determine which policy was the actual source
                source_policy = None
                if policies_consulted and final != self.NOT_FOUND_FINAL:
                    # The last successful tool call is the source
                    for p in reversed(policies_consulted):
                        source_policy = p
                        break
                return {
                    "final_answer": final,
                    "source_policy": source_policy if final != self.NOT_FOUND_FINAL else None,
                    "sources": all_sources,
                    "chain_of_thought": cot,
                }

            # Execute every tool call the LLM requested this turn
            for call in ai_msg.tool_calls:
                tname = call["name"]
                targs = call["args"]
                query = targs.get("query", question)
                policy_label = "Medical" if tname == "search_medical_policy" else "Dental"

                cot.append(
                    f"**Step {len(cot)+1} — LLM chose tool `{tname}`** with query "
                    f"_{query}_ → calling {policy_label} agent."
                )

                result = self._run_tool_with_sources(tname, query)
                answer_text = result["answer"]
                cot.append(
                    f"**Step {len(cot)+1} — {policy_label} agent returned:** "
                    f"_{answer_text if len(answer_text) < 220 else answer_text[:200] + '...'}_"
                )

                if result["found"]:
                    policies_consulted.append(policy_label)
                    all_sources.extend(result["sources"])
                else:
                    cot.append(
                        f"**Step {len(cot)+1} — `NOT_FOUND` from {policy_label}.** "
                        f"Orchestrator should call the other tool next."
                    )

                messages.append(ToolMessage(content=answer_text, tool_call_id=call["id"]))

        # Safety net: ran out of iterations
        cot.append(f"**Step {len(cot)+1} — Reached max_iters={max_iters} without a final answer.**")
        return {
            "final_answer": self.NOT_FOUND_FINAL,
            "source_policy": None,
            "sources": all_sources,
            "chain_of_thought": cot,
        }

"""## 7. Build the system

Place `medical_policy.pdf` and `dental_policy.pdf` in the working directory (or upload them via
the UI in section 9), then run the cell below.
"""

clear_indexes()  # uncomment if you want to re-embed the PDFs

orchestrator = build_system()    # uncomment when your PDFs are ready

"""## 8. Classroom demo — **strict vs. weak `NOT_FOUND` prompt** (upgrade #2)

Run this cell **after** `build_system()` to demonstrate why the strict prompt matters.

We ask the *same* out-of-scope question to two Dental specialists: one with the strict prompt and
one with the weakened prompt. The strict one returns `NOT_FOUND` (so the orchestrator's fallback
chain works); the weak one hedges or invents an answer (so the fallback chain breaks).

"""

def run_not_found_demo(question: str = "Does the plan cover space travel insurance?"):
    if dental_agent is None:
        print("Build the system first.")
        return

    llm = ChatOpenAI(model=LLM_MODEL, temperature=0)
    strict = dental_agent  # already strict
    weak   = PolicyAgent("Dental", dental_agent.vectorstore, llm,
                         prompt_template=STRICT_PROMPT)

    print("=" * 70)
    print("OUT-OF-SCOPE QUESTION:", question)
    print("=" * 70)

    strict_out = strict.ask(question)
    print("\n--- STRICT prompt (correct: returns NOT_FOUND) ---")
    print("Answer:", strict_out["answer"])
    print("Triggers fallback?", "YES ✅" if not strict_out["found"] else "NO ❌")

    weak_out = weak.ask(question)
    print("\n--- WEAK prompt (broken: hedges or invents) ---")
    print("Answer:", weak_out["answer"])
    print("Triggers fallback?", "YES ✅" if not weak_out["found"] else "NO ❌ — fallback breaks here")


# run_not_found_demo()  # uncomment after build_system()

"""## 9. User interface (gradio)

The UI now also has a **"Clear & rebuild indexes"** button so you can force re-embedding when the
PDFs change. By default, indexes are reloaded from disk if they exist.

"""

!pip install -q gradio  # run once

import gradio as gr

# ---------- Handlers (thin wrappers around the existing functions) ----------
def ui_build(medical_file, dental_file):
    """Build / load the system. medical_file / dental_file are NamedString paths from gr.File."""
    logs = []
    try:
        med_path = medical_file.name if medical_file is not None else MEDICAL_PDF
        den_path = dental_file.name  if dental_file  is not None else DENTAL_PDF

        # Capture build_system's print output so we can show it in the UI
        import io, contextlib
        buf = io.StringIO()
        with contextlib.redirect_stdout(buf):
            build_system(med_path, den_path)
        return buf.getvalue() or "System ready."
    except Exception as e:
        return f"❌ Build failed: {e}"


def ui_rebuild(medical_file, dental_file):
    """Wipe persisted indexes and rebuild from scratch."""
    import io, contextlib
    buf = io.StringIO()
    try:
        with contextlib.redirect_stdout(buf):
            clear_indexes()
            med_path = medical_file.name if medical_file is not None else MEDICAL_PDF
            den_path = dental_file.name  if dental_file  is not None else DENTAL_PDF
            build_system(med_path, den_path)
        return buf.getvalue() or "Indexes rebuilt."
    except Exception as e:
        return f"❌ Rebuild failed: {e}\n\n{buf.getvalue()}"


def ui_demo():
    """Run the strict-vs-weak NOT_FOUND classroom demo."""
    import io, contextlib
    buf = io.StringIO()
    try:
        with contextlib.redirect_stdout(buf):
            run_not_found_demo()
        return buf.getvalue()
    except Exception as e:
        return f"❌ Demo failed: {e}"


def ui_ask(question):
    """Send a question to the orchestrator and return (answer_md, cot_md, sources_md)."""
    if orchestrator is None:
        msg = "⚠️ Build the system first using the button above."
        return msg, "", ""
    if not question or not question.strip():
        return "⚠️ Please type a question.", "", ""

    try:
        result = orchestrator.answer(question.strip())
    except Exception as e:
        return f"❌ Error: {e}", "", ""

    # --- Final answer with badge ---
    if result["source_policy"] == "Medical":
        badge = "🩺 **Medical Policy**"
    elif result["source_policy"] == "Dental":
        badge = "🦷 **Dental Policy**"
    else:
        badge = "🚫 **No policy match**"
    answer_md = f"### Final answer\n{badge}\n\n> {result['final_answer']}"

    # --- Chain of thought ---
    cot_md = "\n".join(f"{i+1}. {step}" for i, step in enumerate(result["chain_of_thought"]))

    # --- Sources with provenance ---
    if result["sources"]:
        lines = []
        for i, s in enumerate(result["sources"], 1):
            file_tag = f" · `{s.get('source_file','?')}`" if s.get("source_file") else ""
            lines.append(
                f"**[{i}]** _{s['policy']}_{file_tag} — page {s['page']}  \n"
                f"<small>{s['snippet']}</small>"
            )
        sources_md = "\n\n".join(lines)
    else:
        sources_md = "_No sources — nothing was retrieved._"

    return answer_md, cot_md, sources_md

# ---------- Layout ----------
with gr.Blocks(title="Multi-Policy RAG Orchestrator", theme=gr.themes.Soft()) as demo:
    gr.Markdown(
        "# 🩺🦷 Multi-Policy RAG Orchestrator\n"
        "Tool-calling orchestrator over Medical + Dental policies, with persistent FAISS indexes."
    )

    with gr.Tab("1. Load policies"):
        gr.Markdown(
            "Upload both PDFs (or leave blank to use `medical_policy.pdf` / `dental_policy.pdf` "
            "already in the working directory), then click **Build / Load system**. "
            "Indexes are persisted in `faiss_indexes/` and reloaded on subsequent runs."
        )
        with gr.Row():
            medical_pdf_in = gr.File(label="Medical PDF", file_types=[".pdf"])
            dental_pdf_in  = gr.File(label="Dental PDF",  file_types=[".pdf"])
        with gr.Row():
            build_btn   = gr.Button("Build / Load system", variant="primary")
            rebuild_btn = gr.Button("Clear & rebuild indexes", variant="secondary")
            demo_btn    = gr.Button("Run NOT_FOUND demo")
        build_log = gr.Textbox(label="Build log", lines=12, interactive=False)

        build_btn.click(ui_build,   inputs=[medical_pdf_in, dental_pdf_in], outputs=build_log)
        rebuild_btn.click(ui_rebuild, inputs=[medical_pdf_in, dental_pdf_in], outputs=build_log)
        demo_btn.click(ui_demo,     inputs=None,                              outputs=build_log)

    with gr.Tab("2. Ask the orchestrator"):
        question_in = gr.Textbox(
            label="Question",
            placeholder="Ask a question about the medical or dental policy ...",
            lines=2,
        )
        ask_btn = gr.Button("Ask", variant="primary")

        answer_out = gr.Markdown(label="Answer")
        with gr.Accordion("🧠 Chain of thought", open=True):
            cot_out = gr.Markdown()
        with gr.Accordion("📄 Retrieved source snippets (with provenance)", open=False):
            sources_out = gr.Markdown()

        ask_btn.click(ui_ask, inputs=question_in,  outputs=[answer_out, cot_out, sources_out])
        question_in.submit(ui_ask, inputs=question_in, outputs=[answer_out, cot_out, sources_out])

        gr.Examples(
            examples=[
                "Is a root canal covered?",
                "What is the annual out-of-pocket maximum?",
                "Does the plan cover orthodontia for adults?",
                "Are MRI scans covered?",
                "Does the plan cover space travel insurance?",
            ],
            inputs=question_in,
        )

# In Colab, share=True gives you a public URL you can open in a new tab.
demo.launch(share=True, debug=False)

demo.close()

clear_indexes()

"""## 10. What changed vs. the previous notebook

| Area | v2 | v3 |
|---|---|---|
| Orchestrator | Deterministic Python class | **LLM with two bound tools** + deterministic safety-net fallback |
| Routing | Always Medical first | LLM picks tool by intent (dental queries skip the medical step) |
| Indexing | Re-embedded every kernel restart | **`save_local` / `load_local`** — embed once, reload in seconds |
| Provenance | `policy` metadata only | `policy` + `source_file` on every chunk, displayed in the UI |
| Teaching demo | (none) | **Strict-vs-weak `NOT_FOUND`** side-by-side cell |

A few things to watch in class:

- **Tool name matters.** The LLM routes off tool *descriptions*, so the docstrings of
  `search_medical_policy` and `search_dental_policy` are part of the system's prompt surface.
  Weaken those descriptions and watch the routing degrade.
- **`NOT_FOUND` is still load-bearing.** Even with the LLM doing the routing, the fallback to the
  other tool still depends on the specialist returning the literal token. The strict-vs-weak demo
  illustrates exactly that fragility.
- **Persistence is one-line in production.** The same `vs.save_local(...)` / `FAISS.load_local(...)`
  pattern is what you'd use behind a FastAPI service — the notebook is now structurally close to
  the real thing.

"""

docs = dental_agent.retriever.invoke("Is a root canal covered?")
for i, d in enumerate(docs):
    print(f"--- chunk {i} ({len(d.page_content)} chars, page {d.metadata.get('page')}) ---")
    print(d.page_content)
    print()

print(dental_agent.ask("Is a root canal covered?"))

docs = dental_agent.retriever.invoke("Is a root canal covered?")
for d in docs: print(len(d.page_content), d.metadata.get("page"), d.page_content[:200])